classDiagram

class Owner {
    +String name
    +int available_time
    +String preferences
    +update_preferences()
}

class Pet {
    +String name
    +String type
    +int age
    +get_info()
    +update_info()
}

class Task {
    +String task_name
    +int duration
    +String priority
    +edit_task()
}

class Scheduler {
    +List tasks
    +int available_time
    +add_task()
    +generate_schedule
}

Owner --> Pet : owns
Pet --> Task : has
Scheduler --> Task : schedules